# ### GET events 
GET http://localhost:8281/events
### GET events after deploy
GET https://us-central1-pancarinca.cloudfunctions.net/app/events

### Get Event by ID
GET http://127.0.0.1:5001/pancarinca/us-central1/app/events/123456789

### Filter Events by Event Type
GET http://127.0.0.1:5001/pancarinca/us-central1/app/api/events?eventType=Conference

### POST events
POST http://localhost:8383/events/addEvent
Content-Type: application/json

{
  "title": "Fries",
  "description": "This is a sample event description",
  "date": "2024-09-11T00:00:00Z",
  "location": "Event Location",
  "organizer": "KFC",
  "eventType": "Workshop"
}

### 5. DELETE A EVENT
DELETE http://localhost:8383/events
Content-Type: application/json

{
  "id": "1234"
}
###
DELETE http://localhost:8383/events/1726071421642

### Delete Event
DELETE https://us-central1-pancarinca.cloudfunctions.net/app/events/123

### Update Event
PUT http://localhost:8383/events/1726071206890
# PUT http://127.0.0.1:5001/pancarinca/us-central1/app/events/123456789
Content-Type: application/json

{
  "title": "New today",
  "description": "Updated event description",
  "date": "2024-09-09T00:00:00Z",
  "location": "New Event Location",
  "organizer": "Updated Organizer Name",
  "eventType": "Workshop"
}
